// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCGB4te-vD4vmGiuOa9L6Q4IWf6rocRA0',
    appId: '1:767368769380:web:243f40317e1cc4e50c9471',
    messagingSenderId: '767368769380',
    projectId: 'social-media-blocker-1c6ef',
    authDomain: 'social-media-blocker-1c6ef.firebaseapp.com',
    storageBucket: 'social-media-blocker-1c6ef.appspot.com',
    measurementId: 'G-93788V6RYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNGQ-dx2_k0axtzWN7No4SP09PY6pOJg',
    appId: '1:767368769380:android:52de61494895c14e0c9471',
    messagingSenderId: '767368769380',
    projectId: 'social-media-blocker-1c6ef',
    storageBucket: 'social-media-blocker-1c6ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUT7eMywUNa3NSI_fj74gpROQ-dVqA2Xc',
    appId: '1:767368769380:ios:d486cf0bebabab8c0c9471',
    messagingSenderId: '767368769380',
    projectId: 'social-media-blocker-1c6ef',
    storageBucket: 'social-media-blocker-1c6ef.appspot.com',
    iosBundleId: 'com.example.socialMediaBlocker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUT7eMywUNa3NSI_fj74gpROQ-dVqA2Xc',
    appId: '1:767368769380:ios:d486cf0bebabab8c0c9471',
    messagingSenderId: '767368769380',
    projectId: 'social-media-blocker-1c6ef',
    storageBucket: 'social-media-blocker-1c6ef.appspot.com',
    iosBundleId: 'com.example.socialMediaBlocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCGB4te-vD4vmGiuOa9L6Q4IWf6rocRA0',
    appId: '1:767368769380:web:5ed7cdff7cff64f90c9471',
    messagingSenderId: '767368769380',
    projectId: 'social-media-blocker-1c6ef',
    authDomain: 'social-media-blocker-1c6ef.firebaseapp.com',
    storageBucket: 'social-media-blocker-1c6ef.appspot.com',
    measurementId: 'G-QL9Y5JLEB1',
  );
}
